### PR TITLE
fix: properly support Snyk CLI standalone binaries

### PR DESCRIPTION
**Pull request by kyegupov**
- [x] Ready for review
- [x] Follows CONTRIBUTING rules
- [x] Reviewed by Snyk internal team

#### What does this PR do?

fix https://snyksec.atlassian.net/browse/BST-529

### CODE REVIEW

**Comment by lili2311** [comment]
@kyegupov please update the commits to mach the semantic release style

**Comment by lili2311** [comment]
@kyegupov please update the commits to mach the semantic release style

**Comment by kyegupov** [comment]
@lili2311 will squash-merge. Renaming commits now would delay us in the Travis queue which is baad.

**Comment by lili2311** [comment]
Tested manually it resolves the issue ❤️

**Pull request merged**
